[info]
molnam = "test"
date = 2026-03-26T19:07:47.793Z

[controls]
vtmax = 0
Jmax = 3.0
stages = 3
mcalc = 8
S = 0.0
vtcalc = 8
NFOLD = [3, 3, 3]

[second_order]
#A = [3000.0, 1.0, 1]
#B = [1500.0, 1.0, 1]
#C = [1000.0, 1.0, 1]

[user_def]
#Nam = [Func, val, unit, scale, stage]
BK = ["Nz^2", 1.75, "GHz", 1.0, 0]
BN = ["N2", 1.25, "GHz", 1.0, 0]
"B±" = ["Npm^2", 0.125, "GHz", 1.0, 0]
F_1 = ["Pα^2",  5.1, "cm-1", 1.0, 2]
F_2 = ["Pβ^2",  5.0, "cm-1", 1.0, 2]
F_3 = ["Pγ^2",  5.2, "cm-1", 1.0, 2]
V3_1 = ["vncα^3",  50.0, "cm-1", 1.0, 2]
V3_2 = ["vncβ^3", 100.0, "cm-1", 1.0, 2]
V3_3 = ["vncγ^3", 200.0, "cm-1", 1.0, 2]
#"BN^(3)" = ["N2 cosα^3", 4.38, "MHz", 1.0, 0]
#"ρz" = ["Pα Nz", -6.0, "GHz", 1.0, 0]
#DK  = ["Nz^4", 0.52, "MHz", 1.0, 0]
#DSK = ["Nz^2 TS^2_0", 0.52, "MHz", 1.0, 0]
F12 = ["Pα Pβ", 0.1, "cm-1", 1.0, 1]
F13 = ["Pα Pγ", 0.2, "cm-1", 1.0, 1]
F23 = ["Pβ Pγ", 0.3, "cm-1", 1.0, 1]

[intensities]
"μz" = ["μz", 1.0]
"μx" = ["μx", 0.8]
"μy" = ["μy", 0.1]
