[info]
molnam = "test"
date = 2026-03-26T19:07:47.793Z

[controls]
vtmax = 0
Jmax = 4.0
stages = 3
RUNmode = "E"
mcalc = 8
S = 0.0
vtcalc = 8
NFOLD = [3, 3]

[user_def]
#Nam = [Func, val, unit, scale, stage]
A    = ["Nz^2", 3000.0, "MHz", 1.0, 0]
B    = ["Nx^2", 1500.0, "MHz", 1.0, 0]
C    = ["Ny2",  1000.0, "MHz", 1.0, 0]
F_1  = ["Pα^2",   5.1, "cm-1", 1.0, 2]
V3_1 = ["vncα^3", 100.0, "cm-1", 1.0, 2]
F_2  = ["Pα^2",   5.0, "cm-1", 1.0, 2]
V3_2 = ["vncβ^3", 200.0, "cm-1", 1.0, 2]
"ρz1" = ["Pα Nz", -6.0, "GHz", 1.0, 0]
"ρz2" = ["Pβ Nz", -5.0, "GHz", 1.0, 0]
"BN^(3)" = [["N2", "N2 cosα^3"], [8.53, -1.0], "MHz", 1.0, 0]
"BK^(3)" = [["Nz", 8.53, "MHz", 1.0, 0],
       ["Nz cosα^3", -1.0, "arb", 1.0, 0]]
DK  = ["Nz^4", 0.52, "MHz", 1.0, 0]
F12 = ["Pα Pβ", 0.1, "cm-1", 1.0, 1]

[intensity]
"μz" = ["μz", 1.4]
"μx" = ["μx", 1.0]
"μz^(3)" = ["μz μcosα^3", 0.2]
#"μy^(3)" = ["μy μsinα^3", 0.1]
