[info]
molnam = "test"
date = 2026-03-26T19:07:47.793Z

[controls]
vtmax = 0
Jmax = 3.0
stages = 2
mcalc = 9
vtcalc = 8
NFOLD = [3]

[second_order]
#A = [3000.0, 1.0, 1]
#B = [1500.0, 1.0, 1]
#C = [1000.0, 1.0, 1]

[user_def]
#Nam = [Func, val, unit, scale, stage]
BK = ["Nz^2", 1.75, "GHz", 1.0, 0]
BN = ["N2", 1.25, "GHz", 1.0, 0]
"B±" = ["Npm^2", 0.125, "GHz", 1.0, 0]
F = ["Pα^2",  5.0, "cm-1", 1.0, 1]
V3 = ["vncα^3", 100.0, "cm-1", 1.0, 1]
#"BN^(3)" = ["N2 cosα^3", 4.38, "MHz", 1.0, 0]
#"ρz" = ["Pα Nz", -6.0, "GHz", 1.0, 0]
#DK  = ["Nz^4", 0.52, "MHz", 1.0, 0]
#DSK = ["Nz^2 TS^2_0", 0.52, "MHz", 1.0, 0]
#F12 = ["Pα Pβ", 0.1, "MHz", 1.0, 2]

[intensities]
"μz" = ["μz", 1.0]
"μx" = ["μx", 0.8]
"μy" = ["μy", 0.1]
